name: Delete All Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
    - name: 清理Actions空间


      uses: MajorScruffy/delete-old-workflow-runs@v0.2.0
      with:
       GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
       repository: ${{ github.repository }}


