name: 清理Actions
on:
  workflow_dispatch:

  schedule:
    - cron: 0 3 */2 * *

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v3
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 0
          retain_days: ${{ env.retain_days }}
