name: Delete All Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
    - name: 清理Actions空间
      continue-on-error: false
      if: env.REPO_TOKEN
      uses: small-5/delete-workflow-runs@main
      with:
        token: ${{ secrets.REPO_TOKEN }}
        repository: ${{ github.repository }}
        retain_min: ${{ env.RETAIN_MINUTE }}

