name: Delete All Workflow Runs

on:
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.REPO_TOKEN }}
          repository: ${{ github.repository }}
          keep_minimum_runs: 0
          baseUrl: https://api.github.com
          retain_days: 30
